"""add category

Revision ID: 41541e86d0c9
Revises: efd0364f80be
Create Date: 2020-03-14 16:52:54.169225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41541e86d0c9'
down_revision = 'efd0364f80be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'category')
    # ### end Alembic commands ###
