"""add time to blogs

Revision ID: efd0364f80be
Revises: 80ccac020517
Create Date: 2020-03-13 20:34:05.270058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd0364f80be'
down_revision = '80ccac020517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'timestamp')
    # ### end Alembic commands ###
